name: Add Copyright Headers

on:
  workflow_dispatch: # ✅ manual trigger

jobs:
  add-headers:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ✅ Allow pushing code back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install glob

      - name: Add missing headers
        run: |
          node .github/workflows/add-copyright.js

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Add missing copyright headers" || echo "No changes to commit"
          git push
