name: Check Copyright on PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base and head branches
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}          

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get list of changed files
        id: changed-files
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep -E '\.ts$|\.js$' || true)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Save changed files to disk
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}" > changed_files.txt

      - name: Install dependencies
        run: npm install

      - name: Run copyright check
        id: check_copyright
        run: node .github/workflows/check-copyright.js changed_files.txt

      - name: Fail PR if missing copyright
        if: failure()
        run: exit 1

      - name: Create Fix PR if needed
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "fix: add/update missing copyright headers"
          title: "Fix: Copyright headers"
          body: |
            This PR automatically adds or updates missing copyright headers in changed files.
          branch: fix/copyright-${{ github.run_id }}
          base: ${{ github.event.pull_request.head.ref }}

      - name: Comment on PR with fix suggestion
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = process.env.GITHUB_RUN_ID;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Copyright headers are missing or outdated.** A fix has been proposed in a separate PR: \`fix/copyright-${runId}\`.Please review and merge the fix or update headers manually.`
            })
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Add "missing-copyright" label
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: missing-copyright
