# .github/workflows/draft-release.yml

name: Draft Release Notes (Manual Trigger)

# The 'workflow_dispatch' event allows you to run this workflow manually from the GitHub UI.
# It also allows defining inputs that the user can provide.
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to draft release notes from (e.g., release, server-acl)'
        required: true
        default: 'release' # Set a sensible default branch name here

jobs:
  draft_new_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating/updating releases
      pull-requests: write # Required for reading PRs and their labels

    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          # Use the 'branch' input provided by the user to checkout the specific branch
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 # Fetch all history for accurate commit range detection

      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          # Crucial: Explicitly tell release-drafter which commit/branch the tag should point to.
          # In this case, it should point to the HEAD of the branch that was checked out.
          target_commitish: ${{ github.event.inputs.branch }}
          # The configuration for release-drafter is still in .github/release-drafter.yml
          # No changes needed there, as release-drafter operates on the history of the
          # branch that is currently checked out by the 'actions/checkout' step.
