name: Weekly LOC Count

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze'
        required: false
        default: 'master'
      days:
        description: 'Number of past days to include'
        required: false
        default: '7'

  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  loc-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the specified branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Show commits from the past N days
        run: |
          BRANCH=${{ github.event.inputs.branch || 'master' }}
          DAYS=${{ github.event.inputs.days || 7 }}
          echo "Analyzing branch: $BRANCH"
          echo "Time range: last $DAYS days"
          git log --since="$DAYS days ago" --pretty=oneline

      - name: Show lines of code added/removed in past N days
        run: |
          DAYS=${{ github.event.inputs.days || 7 }}
          OLDEST_COMMIT=$(git log --since="$DAYS days ago" --format="%H" | tail -1)
          echo "### LOC changes for the past $DAYS days" >> $GITHUB_STEP_SUMMARY
          if [ -z "$OLDEST_COMMIT" ]; then
            echo "No commits found in the past $DAYS days." | tee -a loc-summary.txt
          else
            echo "Changes from commit $OLDEST_COMMIT to HEAD:" | tee -a loc-summary.txt
            git diff --shortstat $OLDEST_COMMIT..HEAD | tee -a loc-summary.txt
          fi
          cat loc-summary.txt >> $GITHUB_STEP_SUMMARY
