name: Weekly LOC Count

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze'
        required: false
        default: 'master'

  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  loc-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the specified branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Show commits from the last 7 days
        run: |
          echo "Analyzing branch: ${{ github.event.inputs.branch || 'master' }}"
          git log --since="7 days ago" --pretty=oneline

      - name: Show lines of code added/removed in last 7 days
        run: |
          OLDEST_COMMIT=$(git log --since="7 days ago" --format="%H" | tail -1)
          if [ -z "$OLDEST_COMMIT" ]; then
            echo "No commits found in the past 7 days."
          else
            echo "Changes from commit $OLDEST_COMMIT to HEAD:"
            git diff --shortstat $OLDEST_COMMIT..HEAD | tee loc-summary.txt
            echo "### LOC changes for the past 7 days" >> $GITHUB_STEP_SUMMARY
            cat loc-summary.txt >> $GITHUB_STEP_SUMMARY
          fi
