name: Release Notes Generator

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate release notes from'
        required: false
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Release Notes
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: ${{ github.event.inputs.branch || 'main' }}
