name: Print Release Notes

on:
  workflow_dispatch:  # This allows manual triggering with branch selection from a dropdown
    inputs:
      branch:
        description: 'Branch to generate release notes from'
        required: true
        default: 'master'  # Default to 'master' if no input is provided

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}  # Use the branch from the input or default to 'master'

      - name: Print the selected branch
        run: |
          echo "Selected branch: ${{ github.event.inputs.branch || 'master' }}"  # Print the selected branch

      - name: Generate clean release notes from commit history
        run: |
          BRANCH="${{ github.event.inputs.branch || 'master' }}"  # Input or default branch
          BASE_BRANCH="master"

          echo "Generating clean release notes for branch: $BRANCH"

          git fetch origin

          NOTES=$(git log --no-merges --cherry-pick --right-only --pretty=format:"- %s (%an)" origin/$BASE_BRANCH...origin/$BRANCH)

          if [ -z "$NOTES" ]; then
            echo "No unique commits found to generate release notes."
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "_No new changes detected._" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "$NOTES" >> $GITHUB_STEP_SUMMARY
          fi

      # Dummy unrelated change in .github/workflows/release.yml | server-acl | Batch 1
