name: Print Release Notes

on:
  workflow_dispatch:  # This allows manual triggering with branch selection from a dropdown
    # No need to define any inputs here, since user will select the branch when running the action.

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || 'master' }}  # This uses the branch selected when triggering the action or defaults to 'master'

      - name: Generate release notes from commit history
        run: |
          BRANCH="${{ github.head_ref || 'master' }}"  # Get the branch that triggered the action, defaulting to 'master'
          BASE_BRANCH="master"  # Default base branch

          echo "Generating release notes for branch: $BRANCH"

          # Find the common ancestor between the input branch and the base branch (master)
          MERGE_BASE=$(git merge-base origin/$BASE_BRANCH origin/$BRANCH)

          if [ -z "$MERGE_BASE" ]; then
            echo "No common ancestor found between $BASE_BRANCH and $BRANCH."
            exit 1
          fi

          # Get the commits between the base branch and the input branch
          NOTES=$(git log --pretty=format:"- %s (%an)" $MERGE_BASE..origin/$BRANCH)

          if [ -z "$NOTES" ]; then
            echo "No new commits found to generate release notes."
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "_No new changes detected._" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "$NOTES" >> $GITHUB_STEP_SUMMARY
          fi
