name: Print Release Notes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate release notes from'
        required: true
        default: 'master'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Print the selected branch
        run: |
          echo "Selected branch: ${{ github.event.inputs.branch || 'master' }}"

      - name: Generate clean release notes with commit links
        run: |
          BRANCH="${{ github.event.inputs.branch || 'master' }}"
          BASE_BRANCH="master"
          REPO_URL="https://github.com/ChaitanyaBabar/bookapp"

          echo "Generating clean release notes for branch: $BRANCH"
          git fetch origin

          NOTES=$(git log --no-merges --cherry-pick --right-only \
            --pretty=format:"- %s ([%%h]($REPO_URL/commit/%%H)) (%%an, %%ad)" \
            --date=short \
            origin/$BASE_BRANCH...origin/$BRANCH)

          if [ -z "$NOTES" ]; then
            echo "No unique commits found to generate release notes."
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "_No new changes detected._" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Release Notes for \`$BRANCH\`" >> $GITHUB_STEP_SUMMARY
            echo "$NOTES" >> $GITHUB_STEP_SUMMARY
          fi
